#include <sourcemod>
#include <sdkhooks>
#include <sdktools>
#include <rankme>
#include <lvl_ranks>

#pragma newdecls required
#pragma semicolon 1

public Plugin myinfo =
{
	name = "Faceit Levels For Kento RankMe",
	author = "Sarrus",
	description = "A plugin that gives players faceit levels based on their ranks generated by kento-rankme.",
	version = "1.0",
	url = "https://github.com/Sarrus1/"
};

enum struct Player
{
	int iPoints;
	int iFaceitLevel;
}

Player g_Players[MAXPLAYERS+1];

int 
	m_nPersonaDataPublicLevel,
	g_iFaceitLevelsMins[10] = {0};

ConVar 
	g_FaceitLevelRank1,
	g_FaceitLevelRank2,
	g_FaceitLevelRank3,
	g_FaceitLevelRank4,
	g_FaceitLevelRank5,
	g_FaceitLevelRank6,
	g_FaceitLevelRank7,
	g_FaceitLevelRank8,
	g_FaceitLevelRank9,
	g_FaceitLevelRank10,
	g_FaceitLevelRoundReload,
	g_FaceitLevelFFAMode,
	g_FaceitLevelBackend;

bool
	bRankMe = true,
	bLevelRank = false;

public void OnPluginStart()
{
	HookEvent("round_end", OnRoundEnd, EventHookMode_Post);
	HookEvent("player_death", OnPlayerDeath, EventHookMode_Post);

	g_FaceitLevelRank1 = CreateConVar("sm_faceit_level_rank_1", "0", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank2 = CreateConVar("sm_faceit_level_rank_2", "1200", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank3 = CreateConVar("sm_faceit_level_rank_3", "1300", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank4 = CreateConVar("sm_faceit_level_rank_4", "1400", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank5 = CreateConVar("sm_faceit_level_rank_5", "1500", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank6 = CreateConVar("sm_faceit_level_rank_6", "1600", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank7 = CreateConVar("sm_faceit_level_rank_7", "1700", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank8 = CreateConVar("sm_faceit_level_rank_8", "1800", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank9 = CreateConVar("sm_faceit_level_rank_9", "1900", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRank10 = CreateConVar("sm_faceit_level_rank_10", "2000", "Minimum amounts of points for a player to be level 1.", 0, true, 0.0);
	g_FaceitLevelRoundReload = CreateConVar("sm_faceit_level_round_reload", "0", "1 to reload the ranks every round, 0 to only reload them on map start", 0, true, 0.0, true, 1.0);
	g_FaceitLevelFFAMode = CreateConVar("sm_faceit_level_ffa_mode", "0", "1 to enable ffa mode, player rank is reloaded every death, 0 to reload everyround.", 0, true, 0.0, true, 1.0);
	g_FaceitLevelBackend = CreateConVar("sm_faceit_level_backend", "rankme", "Which backend to use. Current options are: 'rankme' or 'level-rank' without the ''.");

	HookConVarChange(g_FaceitLevelRank1, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank2, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank3, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank4, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank5, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank6, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank7, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank8, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank9, ReloadSkillLevelsMins_ConvarChange);
	HookConVarChange(g_FaceitLevelRank10, ReloadSkillLevelsMins_ConvarChange);

	AutoExecConfig(true, "FaceitLevels-kento-rankme");

	m_nPersonaDataPublicLevel = FindSendPropInfo("CCSPlayerResource", "m_nPersonaDataPublicLevel");
	
	char szBuffer[64];
	GetConVarString(g_FaceitLevelBackend, szBuffer, sizeof(szBuffer));
	if (StrEqual(szBuffer, "level-rank", false))
	{
		bRankMe = false;
		bLevelRank = true;
		PrintToServer("Now using Level-Rank");
	}
	else
	{
		bRankMe = true;
		bLevelRank = false;
		PrintToServer("Now using RankMe");
	}

	ReloadSkillLevelsMins();
	for(int i=1; i<MAXPLAYERS+1; i++)
	{
		if(bRankMe)
			RefreshSkillLevels(i);
		else if(bLevelRank)
			RefreshSkillLevels(i);
	}
}

public Action OnPlayerDeath(Handle event, const char[] name, bool dontBroadcast)
{
	int iUserID = GetEventInt(event, "userid"), iClient;
	iClient = GetClientOfUserId(iUserID);
	if(GetConVarBool(g_FaceitLevelFFAMode) && IsValidClient(iClient))
		RefreshSkillLevels(iClient);
	return Plugin_Continue;
}


public void ReloadSkillLevelsMins_ConvarChange(ConVar convar, const char[] oldValue, const char[] newValue)
{
	ReloadSkillLevelsMins();
}


public void ReloadSkillLevelsMins()
{
	g_iFaceitLevelsMins[0] = GetConVarInt(g_FaceitLevelRank1);
	g_iFaceitLevelsMins[1] = GetConVarInt(g_FaceitLevelRank2);
	g_iFaceitLevelsMins[2] = GetConVarInt(g_FaceitLevelRank3);
	g_iFaceitLevelsMins[3] = GetConVarInt(g_FaceitLevelRank4);
	g_iFaceitLevelsMins[4] = GetConVarInt(g_FaceitLevelRank5);
	g_iFaceitLevelsMins[5] = GetConVarInt(g_FaceitLevelRank6);
	g_iFaceitLevelsMins[6] = GetConVarInt(g_FaceitLevelRank7);
	g_iFaceitLevelsMins[7] = GetConVarInt(g_FaceitLevelRank8);
	g_iFaceitLevelsMins[8] = GetConVarInt(g_FaceitLevelRank9);
	g_iFaceitLevelsMins[9] = GetConVarInt(g_FaceitLevelRank10);
	PrintToServer("Faceit ranks minimums have been reloaded.");
}


public Action OnRoundEnd(Handle event, const char[] name, bool dontBroadcast)
{
	if(GetConVarBool(g_FaceitLevelRoundReload))
	{
		for(int i=0; i<MAXPLAYERS+1; i++)
		{
			RefreshSkillLevels(i);
		}
	}
	return Plugin_Continue;
}

public void OnMapStart()
{
	char sBuf[PLATFORM_MAX_PATH];
	
	for(int i = 0; i < 10; i++)
	{
		FormatEx(sBuf, sizeof sBuf, "materials/panorama/images/icons/xp/level%i.png", 5001 + i);
		
		AddFileToDownloadsTable(sBuf);
	}
	
	SDKHook(GetPlayerResourceEntity(), SDKHook_ThinkPost, Hook_OnThinkPost);
}

public Action RankMe_OnPlayerLoaded(int iClient)
{
	RequestFrame(RefreshSkillLevels, iClient);
}


public void RefreshSkillLevels(int iClient)
{
	int iPoints = 0;
	if(bRankMe)
	{
		if(IsValidClient(iClient)&&RankMe_IsPlayerLoaded(iClient))
			iPoints = RankMe_GetPoints(iClient);
	}
	else if(bLevelRank)
	{
		if(IsValidClient(iClient)&&LR_GetClientStatus(iClient))
			iPoints = LR_GetClientInfo(iClient, ST_EXP);
	}

	g_Players[iClient].iPoints = iPoints;

	for(int i=9; i>=0; i--)
	{
		if(g_Players[iClient].iPoints >= g_iFaceitLevelsMins[i])
		{
			g_Players[iClient].iFaceitLevel = i+1;
			return;
		}
	}
	g_Players[iClient].iFaceitLevel = 1;
}


void Hook_OnThinkPost(int iEnt)
{
	for (int i = 1; i <= MaxClients; i++)
	{
		if(IsValidClient(i))
		{
			SetEntData(iEnt, m_nPersonaDataPublicLevel + i * 4, g_Players[i].iFaceitLevel + 5000);
		}
	}
}


public bool IsValidClient(int client)
{
	return (client >= 0 && client <= MaxClients && IsClientConnected(client) && IsClientAuthorized(client) && IsClientInGame(client) && !IsFakeClient(client));
}